language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq -y $REMOVE
  - sudo apt-get autoremove -qq
  - sudo apt-get install -qq -y gengetopt help2man $EXTRA
env:
  - EXTRA="libjson0-dev libssl-dev"
script: ./build-aux/travis
